# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6C3jjw8_UUz16xFvrF7tUZRN3hQu3JP
"""

1.	# Print in reverse: 	
'python'[::-1]

2.	# Define variables apples and oranges and using format method print following string:	
apples = 7
oranges = 5
fruits = apples + oranges	
print('I have {0} apples and {1} oranges, therefore I have {2} fruits.'.format(apples, oranges, fruits))

3.# Convert list of characters (['a', 'b', 'c', 'd']) to string ('abc'):	
my_list= ['a', 'b', 'c', 'd']
my_list[0] + my_list[1] + my_list[2]

4.# Get difference between two lists:	
num2 = {1, 4, 8, 2}
num1 = {1, 2, 3, 4, 8, 12}
set(num1 & num2)

5.#	Add an item to a tuple: 		
my_numbers = [4, 6, 2, 8, 3, 1]
my_numbers.append(0)
print(my_numbers)

6.#	Convert a tuple to a string:	
P1 = ('p', 'y', 't', 'h', 'o', 'n')
def convertion(P1):
  word1 = ''.join(P1)
  return word1;

word1 = convertion(P1)
print(word1)

7.# Combine dictionaries:
names1 = {'Jack': 25, 'John': 26, 'Emily': 23}
names2 = {'Carol': 28, 'Walter': 22}
names_com = names1.update(names2)
print(names1)

8.# Sum all the items in a dictionary:
ice_cream_price = {'Chocolate': 200, 'Strawberry': 188, 'Vanilla': 175, 'Caramel': 180}	
sum(ice_cream_price.values())

9.#	Remove item(s) from set. Can you guess which item will be removed?
set_numbers = {1, 2, 3, 4, 5}
set_letters = {'p', 'y', 't', 'h', 'o', 'n'}
set_numbers2 = {1, 2, 3, 4, 5}

set_numbers.remove(1)
set_numbers2.discard(2)
set_letters.pop() # removes the last added item, if there isn’t one, removes a random items.

print(set_letters)
print(set_numbers2)
print(set_numbers)

10.# split list into 3 different variables:	
color = [
    ("Black", "#000000", "rgb(0, 0, 0)"), 
    ("Red", "#FF0000", "rgb(255, 0, 0)"), 
    ("Yellow", "#FFFF00", "rgb(255, 255, 0)")
]
Color1, color2, color3 = color
print(color)

11.#	test whether every element of first set is in second set and vice versa using using relational operators:
set_a = set(['Chocolate', 'Strawberry', 'Vanilla', 'Caramel'])
set_b = set(['Vanilla', 'Caramel','Chocolate', 'Strawberry'])
set_c = set(['Chocolate'])
set_a.intersection(set_c)
print(set_a & set_c)